name: URL Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # 每两个小时 UTC 时间运行一次

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 安装依赖
        run: npm install

      - name: 运行脚本
        run: npm run check

      - name: 提交日志
        env:
         TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add log.md
          git commit -m "日志更新 $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "无变化"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
